config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'authorizations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show] do
    resources :event_bookings, except: [:show, :destroy]
  end

  resources :profiles, except: :destroy

  resources :forums, only: [:index, :show] do
    resources :posts, only: [:show, :create, :update, :destroy]
  end

  resources :posts, only: [] do
    resources :replies, only: [:create]
  end

  resources :matches, only: [:new, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :donations, only: [:new, :create, :show] do
    resources :payments, only: [:new, :create]
  end

  resources :questions, only: [:show]
  resources :user_answers, only: [:create]

  get '/events/my_events', to: 'events#my_events', as: :events_my_events
  get '/dashboard', to: 'profiles#dashboard', as: :profiles_dashboard
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :match
  belongs_to :user

  validates :content, presence: true
  validates :match_id, presence: true
  validates :user_id, presence: true
  validates :identifier, presence: true

  after_create :notify_pusher, on: :create

  def notify_pusher
    json = as_json
    json["avatar_url"] = user.photo.url
    Pusher.trigger("message", "new", json)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_match

  def index
    if current_user == @match.mentor
      @counterparty = @match.mentee
    else
      @counterparty = @match.mentor
    end

    @messages = policy_scope(Message).where(match: @match).order(created_at: :desc)
    @message = Message.new
    authorize @match, :is_match?
  end

  def create
    @message = Message.new(message_params)
    @message.user = current_user
    @message.match = @match
    authorize @message
    respond_to do |format|
      if @message.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_match
    @match = Match.find(params[:match_id])
  end

  def message_params
    params.require(:message).permit(:content, :identifier)
  end
end

app/views/messages/_message.html.erb
<% sender = message.user == current_user ? "me" : "her" %>
<div class="chat-bubble-wrapper d-flex chat-container <%= sender %>">
   <div class="chat-image d-flex flex-column align-items-center <%= sender %>">
      <%= cl_image_tag message.user.photo %>
<!--        <div class="chat-username"><%= message.user.identifier %></div> -->
    </div>
    <div class="chat-bubble d-flex flex-column justify-content-between <%= sender %>">
    <div class="chat-message"><%= message.content %></div>
    <div class="chat-timestamp <%= sender %>"><%= message.created_at.strftime("%b %e, %l:%M %p") %></div>
  </div>
</div>

app/views/messages/index.html.erb
<% content_for :meta_title, "Messages | Ellevate" %>
<div class="container mt-5">
  <div class="d-flex row">
    <div class="col-12 col-md-4">
      <div class="mr-1 sticky">

        <div class="card-mentor-chat">
          <h6>You are chatting with </h6>
          <div class="circle">
            <%= cl_image_tag @counterparty.photo, class: "round" %>
          </div>
          <div>
            <h6 class="font-weight-bold my-0"><%= @counterparty.first_name %> <%= @counterparty.last_name %></h6>
            <p class="my-0"><%= @counterparty.profile.current_title %> at <%= @counterparty.profile.current_employer %></p>
            <p class="mt-0 mb-2"><%= @counterparty.profile.city %>, <%= @counterparty.profile.state %></p>
          </div>
            <%= link_to "View Profile", profile_path(@counterparty.profile), class: "btn btn-ghost btn-block mt-4 mb-1" %>
        </div>
      </div>

    </div>

    <div class="col-12 col-md-8">
        <div class="chat-wrapper">
          <%= form_with(model: [@match, @message], remote: true, format: :json, id: 'chat-form') do |form| %>
            <% if @message.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@message.errors.count, "error") %> prohibited this chat from being saved:</h2>
                <ul>
                  <% @message.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <div class="chat-bubble-wrapper head d-flex flex-row chat-container me">
              <div id="message-area">
               <%= form.text_area :content, id: :message, class: "form-control p-4", required: true, placeholder: "Type a message...", autocomplete: 'off', rows: 4 %>
               <%= form.hidden_field :identifier, id: :identifier, value: current_user.identifier %>
               <div class="d-flex justify-content-end mt-3">
                <%= form.submit 'Send Message', class: "btn-solid small" %>
               </div>
              </div>
             <div class="chat-image d-flex flex-column align-items-center me">
                <%= cl_image_tag current_user.photo %>
              </div>
            </div>
          <% end %>

          <div class="chat-box" data-match_id="<%= @match.id %>" data-current_user="<%= current_user.id %>">
           <% if @messages.empty?  %>

             <div class="chat-bubble-wrapper">
               <div class="chat-bubble ellevate">
                 <div class="chat-message">
                 <% if current_user.mentee? %>

                 Congratulations! You have just been connected to a mentor at Ellevate. Now it's the time to send your mentor a message! You can start by introducing yourself and your background. You can even propose a short call with her. Good luck! - Ellevate
                 <% else %>
                 Congratulations! You have just been matched to a mentee. She will usually start the conversation, but please feel free to reach out to her!  - Ellevate
                 <% end  %>
               </div>
                 <div class="chat-timestamp her mt-2"><%= Time.now.strftime("%b %e, %l:%M %p") %></div>
               </div>

             </div>

           <% end %>
           <% @messages.each do |message| %>
             <%= render 'messages/message', message: message %>
           <% end %>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/messages/index2.html.erb
<div class="chat-wrapper">
 <div class="chat-box" data-match_id="<%= @match.id %>" data-current_user="<%= current_user.id %>">
   <% if @messages.empty? %>

     <div class="chat-bubble-wrapper">
       <div class="chat-bubble parking-share">
         <div class="chat-username">Parking Share</div>
         <div class="chat-message">Your chat is here!</div>
       </div>
       <div class="chat-timestamp her"><%= Time.now.strftime("%m-%e-%Y %H:%M") %></div>
     </div>

   <% end %>
   <% @messages.each do |message| %>
     <%= render 'messages/message', message: message %>
   <% end %>
 </div>

 <%= form_with(model: [@match, @message], remote: true, format: :json, id: 'chat-form') do |form| %>
   <% if @message.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(@message.errors.count, "error") %> prohibited this chat from being saved:</h2>
       <ul>
         <% @message.errors.full_messages.each do |message| %>
           <li><%= message %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

</div>