config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'authorizations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show] do
    resources :event_bookings, except: [:show, :destroy]
  end

  resources :profiles, except: :destroy

  resources :forums, only: [:index, :show] do
    resources :posts, only: [:show, :create, :update, :destroy]
  end

  resources :posts, only: [] do
    resources :replies, only: [:create]
  end

  resources :matches, only: [:new, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :donations, only: [:new, :create, :show] do
    resources :payments, only: [:new, :create]
  end

  resources :questions, only: [:show]
  resources :user_answers, only: [:create]

  get '/events/my_events', to: 'events#my_events', as: :events_my_events
  get '/dashboard', to: 'profiles#dashboard', as: :profiles_dashboard
end

app/models/forum.rb
class Forum < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if params[:search].present?
      @posts = policy_scope(Post).global_search(params[:search])
    else
      @forums = policy_scope(Forum)
      # @forum_posts = policy_scope(Post)
    end
  end

  def show
    @forums = policy_scope(Forum)
    @forum = Forum.find(params[:id])
    if params[:search].present?
      posts = policy_scope(Post).global_search(params[:search])
      @results = posts.where(forum_id: @forum.id)
    else
      @posts = Post.where(forum_id: @forum.id)
    end
    @post = Post.new # for the form
    @replies = Reply.all

    authorize @forum
  end
end

app/views/forums/index.html.erb
<div class="container">
<h1 class="pt-5" style="text-align: center;">Forums</h1>

<% content_for :meta_title, "Community Forums | Ellevate" %>
<div class="forum-searchbar">
  <%= render 'components/searchbar' %>
</div>

<div class="container d-flex-wrap justify-content-center" style="min-height: 400px;">
  <% if !@posts.nil? %>
    <% if @posts.empty? %>
      <div class="d-flex justify-content-center pt-3">
        <p style="font-size: 18px;">No results for this search :(</p>
      </div>
    <% elsif @posts.count == 1 %>
      <p class="pt-3" style="text-align: center;font-size: 18px;">Your search returned 1 result!</p>
      <div class="d-flex justify-content-center pt-3">
        <span><%= render 'components/card-post', post: @posts.first %></span>
      </div>
    <% else %>
      <div class="d-flex justify-content-center pt-3">
        <ul>
          <p class="pt-3" style="text-align: center;font-size: 18px;">Your search returned <%= @posts.count %> results!</p>
          <% @posts.each do |post| %>
            <span><%= render 'components/card-post', post: post %></span>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="d-flex justify-content-center pt-3">
      <span><%= link_to "Back to Forums", forums_path, class: "text-dark" %></span>
    </div>
  <% else %>
    <ul class="forum-categories">
      <% @forums.each do |forum| %>
        <%= render 'components/card-category', forum: forum %>
      <% end %>
    </ul>
    <% end %>
</div>
<div class="d-flex justify-content-center">
    <%= link_to "Back to Home", root_path, class: "btn-solid mt-4 mb-5" %>
</div>
</div>

app/views/forums/show.html.erb
<% content_for :meta_title, "#{@forum.name} | Ellevate" %>
<div class="container">
  <div class="row">
    <div class="col-3 side-bar">
      <%= render "components/side-bar", forums: @forums %>
    </div>

    <div class="col-9 forum-show">
      <div class="dashboard-welcome d-flex flex-row">
        <div class="col-6">
          <img src="<%= asset_path(@forum.photo) %>" alt="">
        </div>
        <div class="content col-6">
          <h2><%= @forum.name %></h2>
        </div>
      </div>

      <div class="forum-searchbar">
        <form class="simple_form search" action="<%= forum_path(@forum) %>" method="get" autocomplete="off">
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search" id="search_query" placeholder="Search within <%= @forum.name.downcase %>..." />
          <button name="button" type="submit" class="btn btn-solid">
            <i class="fas fa-search"></i> Search
          </button>
        </div>
        </form>
      </div>

      <% if @results.nil? && !@posts.empty?%>
      <div class="d-flex row justify-content-end mr-3 mb-2">
          <%= render 'components/modal-new-post' %>
      </div>
        <div class="card-post table-header disabled">
          <div class="user">
            <p>User</p>
          </div>
          <div class="post-title">
            <h6 class="d-flex align-items-center">Topic</h6>
          </div>
          <div class="post-number">
            <h4>Replies</h4>
          </div>
          <div class="post-date">
            <h4>Activity</h4>
          </div>
        </div>
        <% @posts.reverse.each do |post| %>
          <%= render 'components/card-forum-post', post: post %>
        <% end %>

      <% elsif @results.nil? && @posts.empty? %>
        <p>No posts for this category</p>
      <% elsif !@results.nil? %>
        <% if @results.empty? %>
          <div class="d-flex justify-content-center pt-3">
            <p class="pt-3" style="text-align: center;font-size: 18px;">No results for this search :(</p>
          </div>
        <% elsif @results.count == 1 %>
          <div class="d-flex justify-content-center pt-3">
            <p class="pt-3" style="text-align: center;font-size: 18px;">Your search returned 1 result!</p>
          </div>
          <div class="d-flex justify-content-center pt-3">
            <li><%= render 'components/card-post', post: @results.first %></li>
          </div>
        <% else %>
          <p class="pt-3" style="text-align: center;font-size: 18px;">Your search returned <%= @results.count %> results!</p>
          <div class="d-flex justify-content-center pt-3">
            <ul>
              <% @results.each do |result| %>
                <span><%= render 'components/card-post', post: result %></span>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
      <div class="d-flex justify-content-center mt-5 mb-5">
        <span><%= link_to "Back to Categories", forums_path, class: "btn-solid mb-5" %></span>
      </div>
    </div>
  </div>
</div>