config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'authorizations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show] do
    resources :event_bookings, except: [:show, :destroy]
  end

  resources :profiles, except: :destroy

  resources :forums, only: [:index, :show] do
    resources :posts, only: [:show, :create, :update, :destroy]
  end

  resources :posts, only: [] do
    resources :replies, only: [:create]
  end

  resources :matches, only: [:new, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :donations, only: [:new, :create, :show] do
    resources :payments, only: [:new, :create]
  end

  resources :questions, only: [:show]
  resources :user_answers, only: [:create]

  get '/events/my_events', to: 'events#my_events', as: :events_my_events
  get '/dashboard', to: 'profiles#dashboard', as: :profiles_dashboard
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  include PgSearch
  pg_search_scope :global_search,
    against: [:title, :description, :city, :host_company],
    using: { tsearch: { prefix: true } }

  has_many :event_bookings, dependent: :destroy
  has_many :users, through: :event_bookings

  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :price, presence: true, numericality: true
  validates :photo, presence: true
  validates :host, presence: true
  validates :host_company, presence: true
  validates :host_photo, presence: true
  validates :city, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if params[:search].present?
      @events = policy_scope(Event).global_search(params[:search])
    else
      @events = policy_scope(Event)
    end
  end

  def show
    @event = Event.find(params[:id])
    @user = current_user
    authorize @event
  end
end

app/views/events/index.html.erb
<div class="container">

  <h1 class="pt-5" style="text-align: center;">Events</h1>

  <% content_for :meta_title, "Events | Ellevate" %>
    <div class="forum-searchbar">
      <form class="simple_form search" action="/events" method="get" autocomplete="off">
        <div class="search-form-control form-group">
          <input class="form-control string required" type="text" name="search" id="search_query" placeholder="Search a city or keyword..." />
          <button name="button" type="submit" class="btn btn-solid">
            <i class="fas fa-search"></i> Search</button>
        </div>
      </form>
  </div>

  <div class="d-flex-wrap justify-content-center" style="min-height: 400px;">
    <% if !@events.nil? %>
      <% if @events.empty? %>
        <div class="d-flex justify-content-center pt-3">
          <p style="font-size: 18px;">No results for this search. Please try another city or keyword.</p>
        </div>
      <% elsif @events.count == 1 %>
        <p class="pt-3" style="text-align: center;font-size: 18px;">Your search returned 1 result!</p>

        <div class="d-flex justify-content-center pt-3">
          <span><%= render 'components/card-event', event: @events.first %></span>
        </div>

      <% else %>
        <div class="d-flex justify-content-center pt-3">
          <ul>
            <p class="pt-3" style="text-align: center;font-size: 18px;">Your search returned <%= @events.count %> results!</p>
            <% @events.each do |event| %>

              <span><%= render 'components/card-event', event: event %></span>

            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="d-flex justify-content-center pt-3">
        <span><%= link_to "Back to All Events", events_path, class: "text-dark" %></span>
      </div>
    <% else %>
      <ul>
        <h3>All upcoming events:</h3>
        <% @events.each do |event| %>
          <%= render 'components/card-category', event: event %>
        <% end %>
      </ul>
      <% end %>
  </div>
  <div class="d-flex justify-content-center">
      <%= link_to "Back to Home", root_path, class: "btn-solid mt-4 mb-5" %>
  </div>
  </div>

</div>

app/views/events/show.html.erb
<% content_for :meta_title, "#{@event.title} | Ellevate" %>
<div class="container">

  <div class="event-info-and-booking">
    <div class="event-info-only">
      <p><%= @event.date.strftime('%A, %B %e, %Y') %></p>
      <h2><%= @event.title %></h2>
      <div class="d-flex event-host-info align-items-center">
        <%= cl_image_tag @event.host_photo, class: "avatar" %>
        <p>Hosted by <strong><%= @event.host %></strong> of <%= @event.host_company %></p>
      </div>
    </div>
    <div class="event-booking">
      <p>Are you going?</p>
    </div>
  </div>

  <div class="event-descrip-and-map">
    <div class="event-description">
    </div>
    <div class="event-map">
    </div>
  </div>

  <div class="d-flex justify-content-center">
      <%= link_to "Back to Events", events_path, class: "btn-solid mt-4 mb-5" %>
  </div>

</div