config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'authorizations'}
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show] do
    resources :event_bookings, except: [:show, :destroy]
  end

  resources :profiles, except: :destroy

  resources :forums, only: [:index, :show] do
    resources :posts, only: [:show, :create, :update, :destroy]
  end

  resources :posts, only: [] do
    resources :replies, only: [:create]
  end

  resources :matches, only: [:new, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :donations, only: [:new, :create, :show] do
    resources :payments, only: [:new, :create]
  end

  resources :questions, only: [:show]
  resources :user_answers, only: [:create]

  get '/events/my_events', to: 'events#my_events', as: :events_my_events
  get '/dashboard', to: 'profiles#dashboard', as: :profiles_dashboard
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_donation

  def new
    authorize @donation
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer:     customer.id,   # You should store this customer id and re-use it.
      amount:       @donation.amount_cents,
      description:  "Payment for donation #{@donation.id}.",
      currency:     @donation.amount.currency
    )

    @donation.update(payment: charge.to_json, state: 'paid')
    authorize @donation
    redirect_to donation_path(@donation)

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_donation_payment_path(@donation)
  end

  private

  def set_donation
   @donation = Donation.find(params[:donation_id])
  end
end

app/views/payments/new.html.erb
<% content_for :meta_title, "Payment Information | Ellevate" %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1487147264018-f937fba0c817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=668&q=80);">
  <div class="all-payment-container d-flex align-items-center justify-content-center">
    <div class="container-donation py-5">
      <div class="col-6 payment-form mx-auto d-flex align-items-center">
        <!-- <div class="donation-logo-wrapper">
          <div class="logo"></div>
          <h2 class="log-in-header">Ellevate</h2>
        </div>
        <div class="p-div donation-paragraph">
          <p class="log-in-p ">Find a mentor and change your life</p>
        </div> -->
        <div class="mx-auto my-auto" id="payment-card">
          <h6>Thank you for choosing to support Ellevate!</h6>
          <%= form_tag donation_payments_path(@donation) do %>
          <article>
            <label class="amount">
              <span>Amount: <%= humanized_money_with_symbol(@donation.amount) %></span>
            </label>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-name="My Ellevate Donation"
            data-email="<%= @donation.donor_email %>"
            data-description="Donation <%= @donation.id %>"
            data-amount="<%= @donation.amount_cents %>"
            data-currency="<%= @donation.amount.currency %>"></script>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>